name: Build Windows EXE

on:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build EXE with PyInstaller
      shell: cmd
      run: |
        pyinstaller --noconfirm --onefile --windowed main.py ^
          --icon=assets/smartQR.ico ^
          --add-data "data.db;." ^
          --add-data "qrcodes;qrcodes" ^
          --add-data "exports;exports" ^
          --add-binary "libs\\libiconv.dll;." ^
          --add-binary "libs\\libzbar64-0.dll;."

    - name: Upload EXE
      uses: actions/upload-artifact@v4
      with:
        name: smartqr-windows-exe
        path: dist/*.exe